# Generated by Django 5.1.3 on 2024-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='issue_type',
            field=models.CharField(choices=[(1, 'New'), (2, 'Repair')], default=2, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='repair_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
