# Generated by Django 5.1.3 on 2024-11-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vehicles', '0003_vehicle_is_repaired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
