# Generated by Django 5.1.3 on 2024-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[(1, 'New'), (2, 'Repair')], default=1, max_length=10),
        ),
    ]
