# Generated by Django 5.1.3 on 2024-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_paid_alter_component_component_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='description',
        ),
        migrations.RemoveField(
            model_name='component',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='component',
            name='price',
        ),
        migrations.AddField(
            model_name='component',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='component',
            name='repair_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
